### ISSUE TITLE
Tic tac toe code

### ISSUE THREAD

**Issue by shayan95** [gruselhaus/gruselhaus#1]
Hi nico, i saw your implementation of minimax in tic tac toe, Ive been trying to do the same on c++ for a 4x4 tic tac toe grid. But my recursive function seems to run infinitely, could you help?

**Comment by gruselhaus** [comment]
I did not implement minimax in TicTacToe. Do you have any source? Maybe I can help you anyway

**Comment by shayan95** [comment]
oh thanks, can you share your email, so that i share the source with you?

**Comment by shayan95** [comment]
I just saw, you only had a commit on it, it was implemented by someone else
https://github.com/CodingTrain/website/blob/main/CodingChallenges/CC_149_Tic_Tac_Toe/Processing/CC_149_Tic_Tac_Toe/CC_149_Tic_Tac_Toe.pde
